name: Caching Primes

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Generate Primes
      run: python3 gen_primes.py > /tmp/prime-nos

    - name: Generate Fibonnaci
      run: python3 gen_primes.py > /tmp/fibo-nos

    - name: Cache prime nos
      id: cache-primes
      uses: actions/cache@v2
      with:
        path: /tmp/prime-nos
        key: prime-nos

    - name: Cache fibonacci nos
      id: cache-fibo
      uses: actions/cache@v2
      with:
        path: /tmp/fibo-nos
        key: prime-nos
          
    - name: check cache
      run: echo "prime cached=${{ steps.cache-primes.outputs.cache-hit }}, ${{ steps.cache-fibo.outputs.cache-hit }}"

  run:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
    - name: Check cache
      uses: actions/cache@v2
      with:
        path: /tmp/prime-nos
        key: prime-nos

    - name: Check fibo cache
      uses: actions/cache@v2
      with:
        path: /tmp/fibo-nos
        key: prime-nos

    - name: check cache
      if: steps.cache-primes.outputs.cache-hit != 'true'
      run: echo "Cache not found"; exit 1

    - name: Print Primes
      run: cat /tmp/prime-nos; cat /tmp/fibo-nos
   
