name: Caching Primes

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Generate Primes
      run: python3 gen_primes.py > /tmp/prime-nos

    - name: Cache prime nos
      id: cache-primes
      uses: actions/cache@v2
      with:
        path: /tmp/prime-nos
        key: prime-nos

    - name: check cache
      run: echo "prime cached={{ steps.cache-primes.outputs.cache-hit }}"

  run:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
    - name: Use cache
      run: echo "Hello World"

